### ISSUE TITLE
advice on tuning launch_params for transform_lbs

### ISSUE THREAD

**Issue by christiankerl** [moderngpu/moderngpu#12]
hi, thanks for the nice library. I'm using transform_lbs in a scenario where every work item needs to perform quite some computation and I'm unsure how to properly set the launch_params. Just reducing the values from the default launch_params_t<128, 11, 8> to something like launch_params_t<128, 3, 3> already increased the performance quite a bit. However, I'm unsure about how to set vt and vt0. should it be odd numbers? always vt > vt0? is the correctness affected if these numbers are not properly set? thanks for your help.

**Comment by seanbaxter** [comment]
vt is the grain-size. It should *usually* be an odd number, because all odds are relatively prime with 32 (the number of shared memory banks), so we can transpose from strided to thread order through shared memory without any special indexing. 

For load-balancing search functions, vt0 is the number of work-items to unroll. Your CTA will process vt * nt 'slots', where each slot is a work-item or a segment. If the number of actual items is <= vt0 * nt, then those first vt0 * nt items will all be processed in an unrolled loop. The remaining (vt - vt0) * nt items may be processed conditionally. 

```cpp
// Check range.
template<int nt, int vt, int vt0 = vt, typename func_t>
MGPU_DEVICE void strided_iterate(func_t f, int tid, int count) {
  // Unroll the first vt0 elements of each thread.
  if(vt0 > 1 && count >= nt * vt0) {
    strided_iterate<nt, vt0>(f, tid);    // No checking
  } else {
    iterate<vt0>([=](int i) {
      int j = nt * i + tid;
      if(j < count) f(i, j);
    });
  }

  iterate<vt0, vt>([=](int i) {
    int j = nt * i + tid;
    if(j < count) f(i, j);
  });
}
```

strided_iterate is my solution for an efficient for loop, which unrolls the first vt0 items. But to enter that unrolled part, the first vt0 items for each thread must all be valid.. Setting a small vt0 means that this unrolled branch will more likely be entered, but the benefit of entering it is smaller, because there is more conditional execution following it. For load-balancing search functions, set vt0 to vt-1, unless your segments are very small, in which case try vt-2. vt0=vt-1 means that if there is at least a ratio of vt-1 work-items to every 1 segment, this fast-path unrolled loop will be taken.

The optimization benefits for very small kernels can be really high here. Eg the interval_move functions will re-order their memory ops and schedule vt-1 LDG ops then vt-1 STG ops, because the compiler no longer has any conditional execution between the loads and stores.

For your kernel, try <128, 3, 2> or <128, 5, 4>.

**Comment by dumerrill** [comment]
Ha, damn those people for whom keystroke-saving two-character names not
obvious...  :)

**Comment by dumerrill** [comment]
One other bit of advice is to experiment with decreasing the VT granularity (items per thread) when:

- Your data types (or the work involved with is each data item) is large.  For example, if you are processing large custom-records, you might start losing SM occupancy (from increased register pressure) or spilling registers (to maintain occupancy of at least 1 CTA per SM, both of which can result in performance dropoff.
- You have small global problem sizes.  If you don't have enough work to fill the GPU, its better to have more thread blocks spread across the GPU that process fewer items each (i.e., more active parallelism).

Cheers, Duane

Forgive my earlier comment, an unintended artifact of using email on the phone to read github comments and make a good-natured jab at Sean :)
